const HEADER_LABELS = {
  en: { home:'Home', blog:'Blog', about:'About us', contact:'Contact', language:'Language', account:'Account', profile:'Profile', myProfile:'My profile', myTrips:'My trips', logout:'Log out', login:'Log in', signUp:'Sign up', menu:'Menu', close:'Close', search:'Search', location:'Your location', detectingLocation:'Detecting...' },
  ru: { home:'Главная', blog:'Блог', about:'О нас', contact:'Контакты', language:'Язык', account:'Аккаунт', profile:'Профиль', myProfile:'Мой профиль', myTrips:'Мои поездки', logout:'Выйти', login:'Войти', signUp:'Регистрация', menu:'Меню', close:'Закрыть', search:'Поиск', location:'Ваше местоположение', detectingLocation:'Определяем...' },
  uk: { home:'Головна', blog:'Блог', about:'Про нас', contact:'Контакти', language:'Мова', account:'Обліковий запис', profile:'Профіль', myProfile:'Мій профіль', myTrips:'Мої подорожі', logout:'Вийти', login:'Увійти', signUp:'Реєстрація', menu:'Меню', close:'Закрити', search:'Пошук', location:'Ваше місцезнаходження', detectingLocation:'Визначаємо...' },
  de: { home:'Startseite', blog:'Blog', about:'Über uns', contact:'Kontakt', language:'Sprache', account:'Konto', profile:'Profil', myProfile:'Mein Profil', myTrips:'Meine Reisen', logout:'Abmelden', login:'Anmelden', signUp:'Registrieren', menu:'Menü', close:'Schließen', search:'Suchen', location:'Ihr Standort', detectingLocation:'Standort wird ermittelt...' },
  fr: { home:'Accueil', blog:'Blog', about:'À propos', contact:'Contact', language:'Langue', account:'Compte', profile:'Profil', myProfile:'Mon profil', myTrips:'Mes voyages', logout:'Se déconnecter', login:'Se connecter', signUp:'Créer un compte', menu:'Menu', close:'Fermer', search:'Rechercher', location:'Votre position', detectingLocation:'Localisation...' },
  es: { home:'Inicio', blog:'Blog', about:'Sobre nosotros', contact:'Contacto', language:'Idioma', account:'Cuenta', profile:'Perfil', myProfile:'Mi perfil', myTrips:'Mis viajes', logout:'Cerrar sesión', login:'Iniciar sesión', signUp:'Registrarse', menu:'Menú', close:'Cerrar', search:'Buscar', location:'Tu ubicación', detectingLocation:'Detectando...' },
  it: { home:'Home', blog:'Blog', about:'Chi siamo', contact:'Contatti', language:'Lingua', account:'Account', profile:'Profilo', myProfile:'Il mio profilo', myTrips:'I miei viaggi', logout:'Esci', login:'Accedi', signUp:'Registrati', menu:'Menu', close:'Chiudi', search:'Cerca', location:'La tua posizione', detectingLocation:'Rilevamento...' },
  pt: { home:'Início', blog:'Blog', about:'Sobre nós', contact:'Contato', language:'Idioma', account:'Conta', profile:'Perfil', myProfile:'Meu perfil', myTrips:'Minhas viagens', logout:'Sair', login:'Entrar', signUp:'Criar conta', menu:'Menu', close:'Fechar', search:'Pesquisar', location:'Sua localização', detectingLocation:'Detectando...' },
  pl: { home:'Strona główna', blog:'Blog', about:'O nas', contact:'Kontakt', language:'Język', account:'Konto', profile:'Profil', myProfile:'Mój profil', myTrips:'Moje podróże', logout:'Wyloguj', login:'Zaloguj', signUp:'Zarejestruj', menu:'Menu', close:'Zamknij', search:'Szukaj', location:'Twoja lokalizacja', detectingLocation:'Ustalanie lokalizacji...' },
  tr: { home:'Ana sayfa', blog:'Blog', about:'Hakkımızda', contact:'İletişim', language:'Dil', account:'Hesap', profile:'Profil', myProfile:'Profilim', myTrips:'Seyahatlerim', logout:'Çıkış yap', login:'Giriş yap', signUp:'Kayıt ol', menu:'Menü', close:'Kapat', search:'Ara', location:'Konumunuz', detectingLocation:'Konum belirleniyor...' },
  sr: { home:'Početna', blog:'Blog', about:'O nama', contact:'Kontakt', language:'Jezik', account:'Nalog', profile:'Profil', myProfile:'Moj profil', myTrips:'Moja putovanja', logout:'Odjavi se', login:'Prijavi se', signUp:'Registruj se', menu:'Meni', close:'Zatvori', search:'Pretraga', location:'Vaša lokacija', detectingLocation:'Određujemo lokaciju...' },
  ar: { home:'الرئيسية', blog:'المدونة', about:'من نحن', contact:'اتصل بنا', language:'اللغة', account:'الحساب', profile:'الملف الشخصي', myProfile:'ملفي الشخصي', myTrips:'رحلاتي', logout:'تسجيل الخروج', login:'تسجيل الدخول', signUp:'إنشاء حساب', menu:'القائمة', close:'إغلاق', search:'بحث', location:'موقعك', detectingLocation:'جارٍ تحديد الموقع...' },
  zh: { home:'首页', blog:'博客', about:'关于我们', contact:'联系我们', language:'语言', account:'账户', profile:'个人资料', myProfile:'我的资料', myTrips:'我的行程', logout:'退出登录', login:'登录', signUp:'注册', menu:'菜单', close:'关闭', search:'搜索', location:'您的位置', detectingLocation:'正在定位...' },
  ja: { home:'ホーム', blog:'ブログ', about:'OptionTripについて', contact:'お問い合わせ', language:'言語', account:'アカウント', profile:'プロフィール', myProfile:'マイプロフィール', myTrips:'マイトリップ', logout:'ログアウト', login:'ログイン', signUp:'新規登録', menu:'メニュー', close:'閉じる', search:'検索', location:'現在地', detectingLocation:'位置情報を確認中...' },
  ko: { home:'홈', blog:'블로그', about:'소개', contact:'문의', language:'언어', account:'계정', profile:'프로필', myProfile:'내 프로필', myTrips:'내 여행', logout:'로그아웃', login:'로그인', signUp:'회원가입', menu:'메뉴', close:'닫기', search:'검색', location:'현재 위치', detectingLocation:'위치 확인 중...' },
  id: { home:'Beranda', blog:'Blog', about:'Tentang kami', contact:'Kontak', language:'Bahasa', account:'Akun', profile:'Profil', myProfile:'Profil saya', myTrips:'Perjalanan saya', logout:'Keluar', login:'Masuk', signUp:'Daftar', menu:'Menu', close:'Tutup', search:'Cari', location:'Lokasi Anda', detectingLocation:'Mendeteksi lokasi...' },
  vi: { home:'Trang chủ', blog:'Blog', about:'Về chúng tôi', contact:'Liên hệ', language:'Ngôn ngữ', account:'Tài khoản', profile:'Hồ sơ', myProfile:'Hồ sơ của tôi', myTrips:'Chuyến đi của tôi', logout:'Đăng xuất', login:'Đăng nhập', signUp:'Đăng ký', menu:'Menu', close:'Đóng', search:'Tìm kiếm', location:'Vị trí của bạn', detectingLocation:'Đang xác định vị trí...' },
  th: { home:'หน้าหลัก', blog:'บล็อก', about:'เกี่ยวกับเรา', contact:'ติดต่อ', language:'ภาษา', account:'บัญชี', profile:'โปรไฟล์', myProfile:'โปรไฟล์ของฉัน', myTrips:'ทริปของฉัน', logout:'ออกจากระบบ', login:'เข้าสู่ระบบ', signUp:'สมัครสมาชิก', menu:'เมนู', close:'ปิด', search:'ค้นหา', location:'ตำแหน่งของคุณ', detectingLocation:'กำลังระบุตำแหน่ง...' },
  hi: { home:'होम', blog:'ब्लॉग', about:'हमारे बारे में', contact:'संपर्क', language:'भाषा', account:'खाता', profile:'प्रोफ़ाइल', myProfile:'मेरी प्रोफ़ाइल', myTrips:'मेरी यात्राएँ', logout:'लॉग आउट', login:'लॉग इन', signUp:'साइन अप', menu:'मेनू', close:'बंद करें', search:'खोजें', location:'आपका स्थान', detectingLocation:'स्थान पता किया जा रहा है...' },
  bn: { home:'হোম', blog:'ব্লগ', about:'আমাদের সম্পর্কে', contact:'যোগাযোগ', language:'ভাষা', account:'অ্যাকাউন্ট', profile:'প্রোফাইল', myProfile:'আমার প্রোফাইল', myTrips:'আমার ভ্রমণ', logout:'লগ আউট', login:'লগ ইন', signUp:'নিবন্ধন', menu:'মেনু', close:'বন্ধ করুন', search:'খুঁজুন', location:'আপনার অবস্থান', detectingLocation:'অবস্থান নির্ধারণ করা হচ্ছে...' },
  hu: { home:'Kezdőlap', blog:'Blog', about:'Rólunk', contact:'Kapcsolat', language:'Nyelv', account:'Fiók', profile:'Profil', myProfile:'Saját profil', myTrips:'Utazásaim', logout:'Kijelentkezés', login:'Bejelentkezés', signUp:'Regisztráció', menu:'Menü', close:'Bezárás', search:'Keresés', location:'Az Ön helye', detectingLocation:'Helymeghatározás...' },
  sv: { home:'Hem', blog:'Blogg', about:'Om oss', contact:'Kontakt', language:'Språk', account:'Konto', profile:'Profil', myProfile:'Min profil', myTrips:'Mina resor', logout:'Logga ut', login:'Logga in', signUp:'Skapa konto', menu:'Meny', close:'Stäng', search:'Sök', location:'Din plats', detectingLocation:'Hämtar plats...' }
};

export const getHeaderUiLabels = language => HEADER_LABELS[(language || 'en').split('-')[0]] || HEADER_LABELS.en;
