// Human-reviewed Booking terminology. Keep service names concise so they work on desktop and mobile.
const LABELS = {
  en: { booking:'Booking', book:'Book your trip', move:'Get around', prepare:'Prepare & protect', help:'Travel help', flights:'Flights', stays:'Hotels', cars:'Car rental', tours:'Tours & activities', trains:'Trains', buses:'Buses', ferries:'Ferries', transfers:'Transfers', bikes:'Bikes & scooters', esim:'eSIM', insurance:'Travel insurance', visa:'Visa & entry', 'city-passes':'City passes', luggage:'Luggage storage', compensation:'Flight compensation', 'trip-planning':'Plan with Vi', destinations:'Destination ideas', 'day-plan':'Plan my day', all:'Explore all travel services', ask:'Ask Vi' },
  ru: { booking:'Бронирование', book:'Билеты и проживание', move:'Транспорт в поездке', prepare:'До поездки', help:'Помощь в пути', flights:'Авиабилеты', stays:'Отели', cars:'Аренда автомобиля', tours:'Туры и развлечения', trains:'Поезда', buses:'Автобусы', ferries:'Паромы', transfers:'Трансферы', bikes:'Велосипеды и самокаты', esim:'eSIM', insurance:'Страхование путешествий', visa:'Визы и правила въезда', 'city-passes':'Туристические карты', luggage:'Камеры хранения', compensation:'Компенсация за задержку рейса', 'trip-planning':'Спланировать с Vi', destinations:'Куда отправиться', 'day-plan':'План на день', all:'Все услуги для путешествий', ask:'Спросить Vi' },
  uk: { booking:'Бронювання', book:'Забронювати подорож', move:'Транспорт', prepare:'Підготовка та захист', help:'Допомога в подорожі', flights:'Авіаквитки', stays:'Готелі', cars:'Оренда авто', tours:'Тури та розваги', trains:'Потяги', buses:'Автобуси', ferries:'Пороми', transfers:'Трансфери', bikes:'Велосипеди та скутери', esim:'eSIM', insurance:'Страхування', visa:'Візи та в’їзд', 'city-passes':'Туристичні картки', luggage:'Зберігання багажу', compensation:'Компенсація за рейс', 'trip-planning':'Планувати з Vi', destinations:'Ідеї для подорожі', 'day-plan':'План на день', all:'Усі сервіси для подорожей', ask:'Запитати Vi' },
  de: { booking:'Buchen', book:'Reise buchen', move:'Unterwegs', prepare:'Vorbereiten & absichern', help:'Reisehilfe', flights:'Flüge', stays:'Hotels', cars:'Mietwagen', tours:'Touren & Aktivitäten', trains:'Züge', buses:'Busse', ferries:'Fähren', transfers:'Transfers', bikes:'Fahrräder & Roller', esim:'eSIM', insurance:'Reiseversicherung', visa:'Visa & Einreise', 'city-passes':'City-Pässe', luggage:'Gepäckaufbewahrung', compensation:'Flugentschädigung', 'trip-planning':'Mit Vi planen', destinations:'Reiseideen', 'day-plan':'Tagesplan', all:'Alle Reiseservices', ask:'Vi fragen' },
  fr: { booking:'Réserver', book:'Réserver votre voyage', move:'Se déplacer', prepare:'Préparer & protéger', help:'Aide au voyage', flights:'Vols', stays:'Hôtels', cars:'Location de voiture', tours:'Visites & activités', trains:'Trains', buses:'Bus', ferries:'Ferries', transfers:'Transferts', bikes:'Vélos & trottinettes', esim:'eSIM', insurance:'Assurance voyage', visa:'Visa & entrée', 'city-passes':'Pass touristiques', luggage:'Consigne à bagages', compensation:'Indemnisation de vol', 'trip-planning':'Planifier avec Vi', destinations:'Idées de voyage', 'day-plan':'Planifier ma journée', all:'Tous les services de voyage', ask:'Demander à Vi' },
  es: { booking:'Reservar', book:'Reserva tu viaje', move:'Cómo moverse', prepare:'Preparar y proteger', help:'Ayuda de viaje', flights:'Vuelos', stays:'Hoteles', cars:'Alquiler de coches', tours:'Tours y actividades', trains:'Trenes', buses:'Autobuses', ferries:'Ferries', transfers:'Traslados', bikes:'Bicicletas y patinetes', esim:'eSIM', insurance:'Seguro de viaje', visa:'Visados y entrada', 'city-passes':'Pases turísticos', luggage:'Consigna de equipaje', compensation:'Compensación de vuelo', 'trip-planning':'Planificar con Vi', destinations:'Ideas de viaje', 'day-plan':'Planear mi día', all:'Todos los servicios de viaje', ask:'Preguntar a Vi' },
  it: { booking:'Prenota', book:'Prenota il viaggio', move:'Come muoversi', prepare:'Preparati e proteggiti', help:'Assistenza di viaggio', flights:'Voli', stays:'Hotel', cars:'Noleggio auto', tours:'Tour e attività', trains:'Treni', buses:'Autobus', ferries:'Traghetti', transfers:'Transfer', bikes:'Bici e monopattini', esim:'eSIM', insurance:'Assicurazione viaggio', visa:'Visti e ingresso', 'city-passes':'Pass turistici', luggage:'Deposito bagagli', compensation:'Rimborso volo', 'trip-planning':'Pianifica con Vi', destinations:'Idee di viaggio', 'day-plan':'Pianifica la giornata', all:'Tutti i servizi di viaggio', ask:'Chiedi a Vi' },
  pt: { booking:'Reservar', book:'Reserve sua viagem', move:'Transporte', prepare:'Preparar e proteger', help:'Ajuda de viagem', flights:'Voos', stays:'Hotéis', cars:'Aluguel de carros', tours:'Passeios e atividades', trains:'Trens', buses:'Ônibus', ferries:'Balsas', transfers:'Traslados', bikes:'Bicicletas e scooters', esim:'eSIM', insurance:'Seguro viagem', visa:'Vistos e entrada', 'city-passes':'Passes turísticos', luggage:'Guarda-volumes', compensation:'Indenização de voo', 'trip-planning':'Planejar com Vi', destinations:'Ideias de viagem', 'day-plan':'Planejar meu dia', all:'Todos os serviços de viagem', ask:'Perguntar ao Vi' },
  pl: { booking:'Rezerwacje', book:'Zarezerwuj podróż', move:'Transport', prepare:'Przygotowanie i ochrona', help:'Pomoc w podróży', flights:'Loty', stays:'Hotele', cars:'Wynajem aut', tours:'Wycieczki i atrakcje', trains:'Pociągi', buses:'Autobusy', ferries:'Promy', transfers:'Transfery', bikes:'Rowery i hulajnogi', esim:'eSIM', insurance:'Ubezpieczenie podróżne', visa:'Wizy i wjazd', 'city-passes':'Karty miejskie', luggage:'Przechowalnia bagażu', compensation:'Odszkodowanie za lot', 'trip-planning':'Planuj z Vi', destinations:'Pomysły na podróż', 'day-plan':'Plan dnia', all:'Wszystkie usługi podróżne', ask:'Zapytaj Vi' },
  tr: { booking:'Rezervasyon', book:'Seyahatini rezerve et', move:'Ulaşım', prepare:'Hazırlık ve güvence', help:'Seyahat yardımı', flights:'Uçuşlar', stays:'Oteller', cars:'Araç kiralama', tours:'Turlar ve aktiviteler', trains:'Trenler', buses:'Otobüsler', ferries:'Feribotlar', transfers:'Transferler', bikes:'Bisiklet ve scooter', esim:'eSIM', insurance:'Seyahat sigortası', visa:'Vize ve giriş', 'city-passes':'Şehir kartları', luggage:'Bagaj emaneti', compensation:'Uçuş tazminatı', 'trip-planning':'Vi ile planla', destinations:'Seyahat fikirleri', 'day-plan':'Günümü planla', all:'Tüm seyahat hizmetleri', ask:'Vi’ye sor' },
  sr: { booking:'Rezervacije', book:'Rezerviši putovanje', move:'Prevoz', prepare:'Priprema i zaštita', help:'Pomoć na putovanju', flights:'Avio-karte', stays:'Hoteli', cars:'Iznajmljivanje auta', tours:'Ture i aktivnosti', trains:'Vozovi', buses:'Autobusi', ferries:'Trajekti', transfers:'Transferi', bikes:'Bicikli i skuteri', esim:'eSIM', insurance:'Putno osiguranje', visa:'Vize i ulazak', 'city-passes':'Turističke kartice', luggage:'Čuvanje prtljaga', compensation:'Naknada za let', 'trip-planning':'Planiraj sa Vi', destinations:'Ideje za putovanje', 'day-plan':'Plan dana', all:'Sve usluge za putovanja', ask:'Pitaj Vi' }
};

export const getTravelServiceLabels = language => LABELS[(language || 'en').split('-')[0]] || LABELS.en;
