// Human-reviewed travel terminology. Sentence case is intentional in every language.
const LABELS = {
  en: { booking:'Booking', book:'Book your trip', move:'Getting around', prepare:'Before your trip', help:'Help while travelling', flights:'Flights', stays:'Hotels', cars:'Car rental', activities:'Tours & activities', tours:'Tours & activities', rail:'Trains', trains:'Trains', bus:'Buses', buses:'Buses', ferries:'Ferries', transfers:'Airport transfers', bikes:'Bikes & scooters', esim:'eSIM', insurance:'Travel insurance', visa:'Visa & entry rules', city_passes:'City passes', 'city-passes':'City passes', luggage_storage:'Luggage storage', luggage:'Luggage storage', flight_compensation:'Flight compensation', compensation:'Flight compensation', plan_day:'Plan my day', 'day-plan':'Plan my day', where_go:'Where can I go?', destinations:'Destination ideas', 'trip-planning':'Plan with Vi', all:'All travel services', ask:'Ask Vi', open:'Search', choose:'Choose with Vi' },
  ru: { booking:'Бронирование', book:'Билеты и проживание', move:'Транспорт', prepare:'Перед поездкой', help:'Помощь в поездке', flights:'Авиабилеты', stays:'Отели', cars:'Аренда авто', activities:'Туры и развлечения', tours:'Туры и развлечения', rail:'Поезда', trains:'Поезда', bus:'Автобусы', buses:'Автобусы', ferries:'Паромы', transfers:'Трансфер из аэропорта', bikes:'Велосипеды и самокаты', esim:'eSIM для поездки', insurance:'Страховка для поездки', visa:'Визы и правила въезда', city_passes:'Туристические карты', 'city-passes':'Туристические карты', luggage_storage:'Камеры хранения', luggage:'Камеры хранения', flight_compensation:'Компенсация за рейс', compensation:'Компенсация за рейс', plan_day:'Спланировать день', 'day-plan':'Спланировать день', where_go:'Куда поехать', destinations:'Идеи для путешествий', 'trip-planning':'Спланировать с Vi', all:'Все услуги', ask:'Спросить Vi', open:'Выбрать', choose:'Подобрать с Vi' },
  uk: { booking:'Бронювання', book:'Квитки та проживання', move:'Транспорт', prepare:'Перед подорожжю', help:'Допомога в подорожі', flights:'Авіаквитки', stays:'Готелі', cars:'Оренда авто', activities:'Тури та розваги', tours:'Тури та розваги', rail:'Потяги', trains:'Потяги', bus:'Автобуси', buses:'Автобуси', ferries:'Пороми', transfers:'Трансфер з аеропорту', bikes:'Велосипеди та самокати', esim:'eSIM для подорожі', insurance:'Страхування подорожі', visa:'Візи та правила в’їзду', city_passes:'Туристичні картки', 'city-passes':'Туристичні картки', luggage_storage:'Зберігання багажу', luggage:'Зберігання багажу', flight_compensation:'Компенсація за рейс', compensation:'Компенсація за рейс', plan_day:'Спланувати день', 'day-plan':'Спланувати день', where_go:'Куди поїхати', destinations:'Ідеї для подорожей', 'trip-planning':'Спланувати з Vi', all:'Усі послуги', ask:'Запитати Vi', open:'Обрати', choose:'Підібрати з Vi' },
  de: { booking:'Buchen', book:'Reise buchen', move:'Unterwegs', prepare:'Vor der Reise', help:'Hilfe unterwegs', flights:'Flüge', stays:'Hotels', cars:'Mietwagen', activities:'Touren & Aktivitäten', rail:'Züge', bus:'Busse', ferries:'Fähren', transfers:'Flughafentransfer', bikes:'Fahrräder & Roller', esim:'eSIM', insurance:'Reiseversicherung', visa:'Visa & Einreise', city_passes:'City-Pässe', luggage_storage:'Gepäckaufbewahrung', flight_compensation:'Flugentschädigung', plan_day:'Tag planen', where_go:'Wohin reisen?', destinations:'Reiseideen', all:'Alle Reiseservices', ask:'Vi fragen', open:'Auswählen', choose:'Mit Vi auswählen' },
  fr: { booking:'Réserver', book:'Réserver le voyage', move:'Se déplacer', prepare:'Avant le voyage', help:'Aide en voyage', flights:'Vols', stays:'Hôtels', cars:'Location de voiture', activities:'Visites & activités', rail:'Trains', bus:'Bus', ferries:'Ferries', transfers:'Transfert aéroport', bikes:'Vélos & trottinettes', esim:'eSIM', insurance:'Assurance voyage', visa:'Visa & entrée', city_passes:'Pass touristiques', luggage_storage:'Consigne à bagages', flight_compensation:'Indemnisation de vol', plan_day:'Planifier la journée', where_go:'Où partir ?', destinations:'Idées de voyage', all:'Tous les services', ask:'Demander à Vi', open:'Choisir', choose:'Choisir avec Vi' },
  es: { booking:'Reservar', book:'Reservar el viaje', move:'Transporte', prepare:'Antes del viaje', help:'Ayuda durante el viaje', flights:'Vuelos', stays:'Hoteles', cars:'Alquiler de coches', activities:'Tours y actividades', rail:'Trenes', bus:'Autobuses', ferries:'Ferries', transfers:'Traslado del aeropuerto', bikes:'Bicicletas y patinetes', esim:'eSIM', insurance:'Seguro de viaje', visa:'Visados y entrada', city_passes:'Pases turísticos', luggage_storage:'Consigna de equipaje', flight_compensation:'Compensación de vuelo', plan_day:'Planear el día', where_go:'Dónde viajar', destinations:'Ideas de viaje', all:'Todos los servicios', ask:'Preguntar a Vi', open:'Elegir', choose:'Elegir con Vi' },
  it: { booking:'Prenota', book:'Prenota il viaggio', move:'Trasporti', prepare:'Prima del viaggio', help:'Aiuto in viaggio', flights:'Voli', stays:'Hotel', cars:'Noleggio auto', activities:'Tour e attività', rail:'Treni', bus:'Autobus', ferries:'Traghetti', transfers:'Transfer aeroporto', bikes:'Bici e monopattini', esim:'eSIM', insurance:'Assicurazione viaggio', visa:'Visti e ingresso', city_passes:'Pass turistici', luggage_storage:'Deposito bagagli', flight_compensation:'Rimborso volo', plan_day:'Pianifica la giornata', where_go:'Dove andare', destinations:'Idee di viaggio', all:'Tutti i servizi', ask:'Chiedi a Vi', open:'Scegli', choose:'Scegli con Vi' },
  pt: { booking:'Reservar', book:'Reservar a viagem', move:'Transporte', prepare:'Antes da viagem', help:'Ajuda na viagem', flights:'Voos', stays:'Hotéis', cars:'Aluguel de carros', activities:'Passeios e atividades', rail:'Trens', bus:'Ônibus', ferries:'Balsas', transfers:'Traslado do aeroporto', bikes:'Bicicletas e scooters', esim:'eSIM', insurance:'Seguro viagem', visa:'Vistos e entrada', city_passes:'Passes turísticos', luggage_storage:'Guarda-volumes', flight_compensation:'Indenização de voo', plan_day:'Planejar o dia', where_go:'Para onde viajar', destinations:'Ideias de viagem', all:'Todos os serviços', ask:'Perguntar ao Vi', open:'Escolher', choose:'Escolher com Vi' },
  pl: { booking:'Rezerwacje', book:'Zarezerwuj podróż', move:'Transport', prepare:'Przed podróżą', help:'Pomoc w podróży', flights:'Loty', stays:'Hotele', cars:'Wynajem aut', activities:'Wycieczki i atrakcje', rail:'Pociągi', bus:'Autobusy', ferries:'Promy', transfers:'Transfer z lotniska', bikes:'Rowery i hulajnogi', esim:'eSIM', insurance:'Ubezpieczenie podróżne', visa:'Wizy i wjazd', city_passes:'Karty miejskie', luggage_storage:'Przechowalnia bagażu', flight_compensation:'Odszkodowanie za lot', plan_day:'Zaplanuj dzień', where_go:'Dokąd pojechać', destinations:'Pomysły na podróż', all:'Wszystkie usługi', ask:'Zapytaj Vi', open:'Wybierz', choose:'Wybierz z Vi' },
  tr: { booking:'Rezervasyon', book:'Seyahati rezerve et', move:'Ulaşım', prepare:'Seyahatten önce', help:'Seyahatte yardım', flights:'Uçuşlar', stays:'Oteller', cars:'Araç kiralama', activities:'Turlar ve aktiviteler', rail:'Trenler', bus:'Otobüsler', ferries:'Feribotlar', transfers:'Havalimanı transferi', bikes:'Bisiklet ve scooter', esim:'eSIM', insurance:'Seyahat sigortası', visa:'Vize ve giriş', city_passes:'Şehir kartları', luggage_storage:'Bagaj emaneti', flight_compensation:'Uçuş tazminatı', plan_day:'Günü planla', where_go:'Nereye gitmeli?', destinations:'Seyahat fikirleri', all:'Tüm hizmetler', ask:'Vi’ye sor', open:'Seç', choose:'Vi ile seç' },
  sr: { booking:'Rezervacije', book:'Rezerviši putovanje', move:'Prevoz', prepare:'Pre putovanja', help:'Pomoć na putu', flights:'Avio-karte', stays:'Hoteli', cars:'Iznajmljivanje auta', activities:'Ture i aktivnosti', rail:'Vozovi', bus:'Autobusi', ferries:'Trajekti', transfers:'Aerodromski transfer', bikes:'Bicikli i skuteri', esim:'eSIM', insurance:'Putno osiguranje', visa:'Vize i ulazak', city_passes:'Turističke kartice', luggage_storage:'Čuvanje prtljaga', flight_compensation:'Naknada za let', plan_day:'Planiraj dan', where_go:'Gde putovati', destinations:'Ideje za putovanje', all:'Sve usluge', ask:'Pitaj Vi', open:'Izaberi', choose:'Izaberi uz Vi' }
};

export const getTravelServiceLabels = language => LABELS[(language || 'en').split('-')[0]] || LABELS.en;
