import React from 'react';
import { Link } from 'react-router-dom';
import LanguageSwitcher from '../LanguageSwitcher/LanguageSwitcher';
import CurrencySwitcher from '../CurrencySwitcher/CurrencySwitcher';
import CountrySwitcher from '../CountrySwitcher/CountrySwitcher';
import { CONTACT_EMAIL, CONTACT_MAILTO } from '../../config/contact';
import './Footer.css';
import './Footer.mobile.css';

const Footer=()=> <>
<div className="footer-subscribe-strip"><div className="container"><div className="footer-subscribe-inner"><div className="footer-subscribe-text"><h4 className="footer-subscribe-title">Stay Inspired</h4><p className="footer-subscribe-subtitle">OptionTrip travel news and personalized updates are being expanded.</p></div><div><a className="footer-subscribe-btn" href="https://blog.optiontrip.com" target="_blank" rel="noopener noreferrer">Travel News</a></div></div></div></div>
<footer className="footer-main" style={{backgroundImage:`url(/images/background_pattern.png)`}}><div className="footer-columns"><div className="container"><div className="footer-columns-grid">
<div className="footer-col footer-col--about"><img src="/images/logo-white.png" alt="OptionTrip" className="footer-logo"/><p className="footer-about-desc">OptionTrip is a young travel technology team building a simpler way to discover, plan, compare, prepare for, and experience trips with Travel Partner Vi at the center.</p><ul className="footer-contact-list"><li><i className="fas fa-envelope footer-contact-icon" aria-hidden="true"></i><a href={CONTACT_MAILTO} aria-label={`Email OptionTrip at ${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></li><li><i className="fas fa-globe footer-contact-icon" aria-hidden="true"></i><a href="https://optiontrip.com">OptionTrip.com</a></li></ul><div className="footer-trust-block"><ul className="footer-trust-list"><li><i className="fas fa-robot"></i> Travel Partner Vi</li><li><i className="fas fa-route"></i> Personalized trip planning</li><li><i className="fas fa-star"></i> Useful travel recommendations</li></ul></div></div>
<div className="footer-col"><h4 className="footer-col-title">Company</h4><ul className="footer-col-links"><li><Link to="/about">About OptionTrip</Link></li><li><Link to="/how-it-works">How It Works</Link></li><li><Link to="/travel-buddy">Travel Partner Vi</Link></li><li><a href="https://blog.optiontrip.com">Travel News</a></li><li><Link to="/contact">Contact Us</Link></li></ul></div>
<div className="footer-col"><h4 className="footer-col-title">Travel</h4><ul className="footer-col-links"><li><Link to="/destinations">Explore Destinations</Link></li><li><Link to="/trip-ideas">Trip Ideas</Link></li><li><Link to="/travel-map">Travel Map</Link></li><li><Link to="/popular-routes">Popular Routes</Link></li><li><Link to="/travel-tips">Travel Tips</Link></li></ul></div>
<div className="footer-col"><h4 className="footer-col-title">Support</h4><ul className="footer-col-links"><li><Link to="/help-center">Help Center</Link></li><li><Link to="/contact">Contact Support</Link></li><li><a href={`${CONTACT_MAILTO}?subject=Travel%20Question`}>Travel Questions</a></li><li><a href={`${CONTACT_MAILTO}?subject=OptionTrip%20Feedback`}>Feedback</a></li></ul></div>
<div className="footer-col"><h4 className="footer-col-title">Legal</h4><ul className="footer-col-links"><li><Link to="/privacy-policy">Privacy Policy</Link></li><li><Link to="/terms">Terms of Service</Link></li><li><Link to="/cookie-policy">Cookie Policy</Link></li><li><Link to="/data-protection">Data Protection</Link></li></ul></div>
</div></div></div><div className="footer-locale-section"><div className="container"><div className="footer-locale-bar"><div className="footer-locale-item"><LanguageSwitcher/></div><div className="footer-locale-item"><CurrencySwitcher/></div><div className="footer-locale-item"><CountrySwitcher/></div></div></div></div><div className="footer-bottom"><div className="container"><div className="footer-bottom-inner"><p className="footer-copyright-text">© 2026 OptionTrip. All rights reserved.</p><div className="footer-social"><a href="https://www.facebook.com/optiontrip" aria-label="Facebook"><i className="fab fa-facebook"></i></a><a href="https://www.x.com/OptionTripCom" aria-label="X"><i className="fab fa-twitter"></i></a><a href="https://www.instagram.com/option_trip" aria-label="Instagram"><i className="fab fa-instagram"></i></a></div></div></div></div></footer></>;
export default Footer;
