import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import './HomeBookingSection.css';

const TODAY = new Date().toISOString().split('T')[0];
const TOMORROW = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const TABS = [
  { id:'flights', label:'Flights', icon:<i className="fa fa-plane" aria-hidden="true"/> },
  { id:'hotels', label:'Stays', icon:<i className="fa fa-bed" aria-hidden="true"/> },
  { id:'cars', label:'Car Rental', icon:<i className="fa fa-car" aria-hidden="true"/> },
  { id:'esim', label:'eSIM', icon:<i className="fa fa-sim-card" aria-hidden="true"/> },
];
const SearchIcon=()=> <i className="fa fa-search" aria-hidden="true"/>;
const SwapIcon=()=> <i className="fa fa-exchange" aria-hidden="true"/>;
const Stepper=({value,min=1,max=9,onChange})=><div className="hbs-stepper"><button type="button" onClick={()=>onChange(Math.max(min,value-1))} disabled={value<=min}>−</button><span>{value}</span><button type="button" onClick={()=>onChange(Math.min(max,value+1))} disabled={value>=max}>+</button></div>;

const HomeBookingSection=()=>{
 const navigate=useNavigate(); const [tab,setTab]=useState('flights');
 const [fFrom,setFFrom]=useState(''),[fTo,setFTo]=useState(''),[fDate,setFDate]=useState(''),[fReturn,setFReturn]=useState(''),[fTripType,setFTripType]=useState('one-way'),[fPassengers,setFPassengers]=useState(1);
 const [hCity,setHCity]=useState(''),[hCheckIn,setHCheckIn]=useState(TODAY),[hCheckOut,setHCheckOut]=useState(TOMORROW),[hGuests,setHGuests]=useState(1),[hRooms,setHRooms]=useState(1);
 const [cPickup,setCPickup]=useState(''),[cDropoff,setCDropoff]=useState(''),[cPickupDate,setCPickupDate]=useState(''),[cReturnDate,setCReturnDate]=useState('');
 const handleFlightSearch=e=>{e.preventDefault();navigate('/flights',{state:{autoFill:true,fromDisplay:fFrom,toDisplay:fTo,departureDate:fDate,returnDate:fReturn,adults:fPassengers,tripType:fTripType}})};
 const handleHotelSearch=e=>{e.preventDefault();navigate('/hotels',{state:{autoFill:true,cityQuery:hCity,checkIn:hCheckIn,checkOut:hCheckOut,adults:hGuests,rooms:hRooms}})};
 const handleCarSearch=e=>{e.preventDefault();navigate('/car-rental',{state:{autoFill:true,pickupLocation:cPickup,dropoffLocation:cDropoff||cPickup,pickupDate:cPickupDate,returnDate:cReturnDate}})};
 const handleEsimGo=e=>{e.preventDefault();navigate('/esim')};
 return <section className="hbs" aria-label="Search and compare travel prices"><div className="hbs__card">
  <div className="hbs__tabs" role="tablist">{TABS.map(t=><button key={t.id} type="button" role="tab" aria-selected={tab===t.id} className={`hbs__tab${tab===t.id?' hbs__tab--active':''}`} onClick={()=>setTab(t.id)}><span className="hbs__tab-icon">{t.icon}</span><span className="hbs__tab-label">{t.label}</span></button>)}</div>
  {tab==='flights'&&<form className="hbs__form" onSubmit={handleFlightSearch}><div className="hbs__trip-type">{['one-way','round-trip'].map(type=><button key={type} type="button" className={`hbs__pill${fTripType===type?' hbs__pill--on':''}`} onClick={()=>setFTripType(type)}>{type==='one-way'?'One way':'Round trip'}</button>)}</div><div className="hbs__row"><div className="hbs__field hbs__field--grow2"><label className="hbs__label">From</label><input className="hbs__input" placeholder="City or airport" value={fFrom} onChange={e=>setFFrom(e.target.value)} required/></div><button type="button" className="hbs__swap" title="Swap origin and destination" onClick={()=>{setFFrom(fTo);setFTo(fFrom)}}><SwapIcon/></button><div className="hbs__field hbs__field--grow2"><label className="hbs__label">To</label><input className="hbs__input" placeholder="City or airport" value={fTo} onChange={e=>setFTo(e.target.value)} required/></div><div className="hbs__field"><label className="hbs__label">Depart</label><input className="hbs__input" type="date" value={fDate} min={TODAY} onChange={e=>setFDate(e.target.value)} required/></div>{fTripType==='round-trip'&&<div className="hbs__field"><label className="hbs__label">Return</label><input className="hbs__input" type="date" value={fReturn} min={fDate||TODAY} onChange={e=>setFReturn(e.target.value)} required/></div>}<div className="hbs__field hbs__field--narrow"><label className="hbs__label">Passengers</label><Stepper value={fPassengers} onChange={setFPassengers}/></div><button type="submit" className="hbs__search-btn"><SearchIcon/> Search prices</button></div></form>}
  {tab==='hotels'&&<form className="hbs__form" onSubmit={handleHotelSearch}><div className="hbs__row"><div className="hbs__field hbs__field--grow3"><label className="hbs__label">Destination</label><input className="hbs__input" placeholder="City, region, or property" value={hCity} onChange={e=>setHCity(e.target.value)} required/></div><div className="hbs__field"><label className="hbs__label">Check in</label><input className="hbs__input" type="date" value={hCheckIn} min={TODAY} onChange={e=>setHCheckIn(e.target.value)} required/></div><div className="hbs__field"><label className="hbs__label">Check out</label><input className="hbs__input" type="date" value={hCheckOut} min={hCheckIn||TODAY} onChange={e=>setHCheckOut(e.target.value)} required/></div><div className="hbs__field hbs__field--narrow"><label className="hbs__label">Guests</label><Stepper value={hGuests} max={8} onChange={setHGuests}/></div><div className="hbs__field hbs__field--narrow"><label className="hbs__label">Rooms</label><Stepper value={hRooms} max={4} onChange={setHRooms}/></div><button type="submit" className="hbs__search-btn"><SearchIcon/> Search prices</button></div></form>}
  {tab==='cars'&&<form className="hbs__form" onSubmit={handleCarSearch}><div className="hbs__row"><div className="hbs__field hbs__field--grow2"><label className="hbs__label">Pick-up location</label><input className="hbs__input" placeholder="City, airport, or hotel" value={cPickup} onChange={e=>setCPickup(e.target.value)} required/></div><div className="hbs__field hbs__field--grow2"><label className="hbs__label">Drop-off location</label><input className="hbs__input" placeholder="Same as pick-up" value={cDropoff} onChange={e=>setCDropoff(e.target.value)}/></div><div className="hbs__field"><label className="hbs__label">Pick-up date</label><input className="hbs__input" type="date" value={cPickupDate} min={TODAY} onChange={e=>setCPickupDate(e.target.value)} required/></div><div className="hbs__field"><label className="hbs__label">Return date</label><input className="hbs__input" type="date" value={cReturnDate} min={cPickupDate||TODAY} onChange={e=>setCReturnDate(e.target.value)} required/></div><button type="submit" className="hbs__search-btn"><SearchIcon/> Search prices</button></div></form>}
  {tab==='esim'&&<form className="hbs__form" onSubmit={handleEsimGo}><div className="hbs__esim-promo"><p className="hbs__esim-promo__text">Travel data plans for 200+ destinations. Compare plans before you buy.</p><button type="submit" className="hbs__search-btn"><SearchIcon/> Compare eSIM plans</button></div></form>}
 </div></section>;
};
export default HomeBookingSection;
