import React, { useState } from 'react';
import PageMeta from '../hooks/usePageMeta';
import { CONTACT_EMAIL, CONTACT_MAILTO } from '../config/contact';

const API_BASE = import.meta.env.VITE_API_URL || 'http://localhost:5000';
const Contact = () => {
  const [formData,setFormData]=useState({name:'',email:'',subject:'',message:''}); const [status,setStatus]=useState('idle'); const [errorMsg,setErrorMsg]=useState('');
  const handleChange=e=>{const {name,value}=e.target;setFormData(p=>({...p,[name]:value}));};
  const handleSubmit=async e=>{e.preventDefault();setStatus('loading');setErrorMsg('');try{const res=await fetch(`${API_BASE}/api/contact`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formData)});const data=await res.json();if(res.ok&&data.success){setStatus('success');setFormData({name:'',email:'',subject:'',message:''});}else{setStatus('error');setErrorMsg(data.message||'Something went wrong. Please try again.');}}catch{setStatus('error');setErrorMsg('Network error. Please try again or email us directly.');}};
  return <><PageMeta title="Contact OptionTrip" description="Contact the OptionTrip team for travel questions, support, feedback, partnerships, or press enquiries." keywords="contact optiontrip, optiontrip support, travel help" path="/contact" />
  <div className="banner pt-8 pb-7 overflow-hidden" style={{backgroundImage:`url(/images/testimonial.png)`}}><div className="container"><div className="banner-content text-center"><h4 className="theme">Contact OptionTrip</h4><h1>How Can We Help?</h1><p>Questions about OptionTrip, Travel Partner Vi, your trip, partnerships, or feedback are welcome.</p></div></div></div>
  <section className="trending pb-6 pt-6"><div className="container"><div className="row"><div className="col-lg-8 mb-4"><div className="box-shadow bg-white p-4 rounded"><h3>Send Us A Message</h3>{status==='success'?<div style={{padding:36,textAlign:'center'}}><h4>Message Sent</h4><p>Thank you. Your message was submitted to the OptionTrip team.</p><button className="nir-btn" onClick={()=>setStatus('idle')}>Send Another Message</button></div>:<form onSubmit={handleSubmit}><div className="row"><div className="col-lg-6 mb-3"><input name="name" className="form-control" placeholder="Your Name" value={formData.name} onChange={handleChange} required /></div><div className="col-lg-6 mb-3"><input type="email" name="email" className="form-control" placeholder="Your Email" value={formData.email} onChange={handleChange} required /></div><div className="col-lg-12 mb-3"><input name="subject" className="form-control" placeholder="Subject" value={formData.subject} onChange={handleChange} required /></div><div className="col-lg-12 mb-3"><textarea name="message" className="form-control" rows="6" placeholder="How can we help?" value={formData.message} onChange={handleChange} required /></div>{status==='error'&&<div className="col-lg-12 mb-3" style={{color:'#b91c1c'}}>{errorMsg}</div>}<div className="col-lg-12"><button className="nir-btn" disabled={status==='loading'}>{status==='loading'?'Sending...':'Send Message'}</button></div></div></form>}</div></div><div className="col-lg-4"><div className="box-shadow bg-white p-4 rounded"><h3>Contact Information</h3><p><strong>Email</strong><br/><a href={CONTACT_MAILTO}>{CONTACT_EMAIL}</a></p><p><strong>About Our Team</strong><br/>We are a young travel technology team building OptionTrip to make travel information, planning, and trip support easier to use.</p><p><strong>Support</strong><br/>Worldwide, online.</p></div></div></div></div></section></>;
};
export default Contact;
