import React from 'react';
import PageMeta from '../hooks/usePageMeta';
import { CONTACT_EMAIL } from '../config/contact';
const sections=[
['Information We Handle','OptionTrip may handle information you provide when using accounts, trip planning, saved preferences, or support, together with technical information needed to operate and protect the service. Location information is used only when the relevant feature and permission allow it.'],
['How Information Is Used','Information may be used to operate OptionTrip, personalize travel planning, maintain accounts and saved trips, respond to support requests, improve the product, measure performance, prevent abuse, and meet legal obligations.'],
['Travel Partner Vi','Vi can process travel details and preferences you provide to generate or refine travel suggestions. AI-generated information can be incomplete or become outdated, so critical entry, safety, schedule, price, and availability information should be verified.'],
['Connected Services','OptionTrip may rely on infrastructure, analytics, AI, email, mapping, travel inventory, affiliate, and other technology providers to deliver features. Information may be transmitted to a provider when necessary for a feature you use and subject to applicable requirements.'],
['Retention And Requests',`Information is retained as needed to provide and protect the service and meet applicable obligations. Privacy, access, correction, or deletion requests can be sent to ${CONTACT_EMAIL}.`],
['Security','We use reasonable safeguards appropriate to the services we operate. No internet service can guarantee absolute security.'],
['Cookies','OptionTrip may use cookies, local storage, and similar technologies for core functions, preferences, measurement, security, and partner attribution where applicable. See the Cookie Policy.'],
['Updates',`This privacy information will be updated as OptionTrip adds or changes features and providers. Questions can be sent to ${CONTACT_EMAIL}.`]
];
const PrivacyPolicyPage=()=> <><PageMeta title="Privacy Policy" description="Privacy information for OptionTrip and Travel Partner Vi." keywords="OptionTrip privacy, data protection" path="/privacy-policy"/><div className="banner pt-8 pb-7 overflow-hidden" style={{backgroundImage:`url(/images/testimonial.png)`}}><div className="container"><div className="banner-content text-center"><h4 className="theme">Privacy</h4><h1>Privacy Information</h1><p>How information is handled across OptionTrip and connected travel features.</p></div></div></div><section style={{padding:'70px 0'}}><div className="container"><div className="row justify-content-center"><div className="col-lg-9"><p style={{fontSize:17,lineHeight:1.8}}>OptionTrip is a growing travel technology platform. This page provides a practical summary of our current privacy approach and will evolve with the services actually deployed.</p>{sections.map(([title,text])=><div key={title} style={{marginBottom:30}}><h3>{title}</h3><p style={{lineHeight:1.8,color:'#666'}}>{text}</p></div>)}</div></div></div></section></>;
export default PrivacyPolicyPage;
