export const TRAVELPAYOUTS_TRIP_OBJECT_MAPPING = Object.freeze({
  flights: 'transport',
  rail: 'transport',
  bus: 'transport',
  ferries: 'transport',
  cars: 'transport',
  bikes: 'transport',
  scooters: 'transport',
  motorcycles: 'transport',
  transfers: 'transport',
  taxis: 'transport',
  hotels: 'stays',
  activities: 'experiences',
  tours: 'experiences',
  packages: 'experiences',
  city_passes: 'experiences',
  esim: 'services',
  insurance: 'services',
  luggage_storage: 'services',
  compensation: 'services',
});
