export const TRAVELPAYOUTS_PROGRAM_LABELS = Object.freeze({
  travelpayouts: 'Aviasales / Travelpayouts',
  tripcom: 'Trip.com',
  twelvego: '12Go',
  qeeq: 'QEEQ',
  economybookings: 'EconomyBookings',
  tiqets: 'Tiqets',
  bikesbooking: 'BikesBooking',
  supertravel: 'SuperTravel',
  youtravel: 'Youtravel',
  insubuy: 'InsuBuy',
  gettransfer: 'GetTransfer',
  kiwitaxi: 'Kiwitaxi',
  klook: 'Klook',
  welcomepickups: 'Welcome Pickups',
  kiwi: 'Kiwi.com',
  airalo: 'Airalo',
  drimsim: 'Drimsim',
  getrentacar: 'GetRentacar',
  airhelp: 'AirHelp',
  gocity: 'Go City',
  ekta: 'EKTA',
  wegotrip: 'WeGoTrip',
  autoeurope: 'AutoEurope',
  radicalstorage: 'Radical Storage',
  intuitravel: 'Intui.travel',
  compensair: 'Compensair',
  saily: 'Saily',
  kkday: 'KKday',
  omio: 'Omio',
  viator: 'Viator',
});
