// Travelpayouts programs observed in OptionTrip's My Programs catalog.
// This list is product metadata only. It must never be used as proof of live API/feed inventory.
export const TRAVELPAYOUTS_AVAILABLE_PROGRAMS = Object.freeze([
  'aviasales',
  'tripcom',
  'twelvego',
  'qeeq',
  'economybookings',
  'tiqets',
  'bikesbooking',
  'supertravel',
  'youtravel',
  'insubuy',
  'gettransfer',
  'kiwitaxi',
  'klook',
  'welcomepickups',
  'kiwi',
  'airalo',
  'drimsim',
  'getrentacar',
  'airhelp',
  'gocity',
  'ekta',
  'wegotrip',
  'autoeurope',
  'radicalstorage',
  'intuitravel',
  'compensair',
  'saily',
  'kkday',
]);
